spring.application.name=backend

# =========================
# DATABASE
# =========================
spring.datasource.url=jdbc:mysql://localhost:3306/petshop_pos
spring.datasource.username=root
spring.datasource.password=rednabcamoih372.

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# SERVER
# =========================
server.port=8080
#---open-in-view disabled 
spring.jpa.open-in-view=false

# ==========================
# DARAJA SANDBOX
# ==========================

mpesa.consumerKey=gGk2Q6bDGr6G9pdIILAdZ7c30YRAqGTpLmPOTDoUXaI9dZor

mpesa.consumerSecret=iZwfpoKC50vqCMYE7NvULpPgW47qGgQy9c0Qxha7qGtG2cYNIgNMuwlg7B64Ay1X

mpesa.shortCode=174379

mpesa.passKey=bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919

mpesa.callbackUrl=https://huddle-agonizing-dynamic.ngrok-free.dev/api/payments/callback
